export const browserCoreExamples = [
  "nova-engine browser status",
  "nova-engine browser start",
  "nova-engine browser stop",
  "nova-engine browser tabs",
  "nova-engine browser open https://example.com",
  "nova-engine browser focus abcd1234",
  "nova-engine browser close abcd1234",
  "nova-engine browser screenshot",
  "nova-engine browser screenshot --full-page",
  "nova-engine browser screenshot --ref 12",
  "nova-engine browser snapshot",
  "nova-engine browser snapshot --format aria --limit 200",
  "nova-engine browser snapshot --efficient",
  "nova-engine browser snapshot --labels",
];

export const browserActionExamples = [
  "nova-engine browser navigate https://example.com",
  "nova-engine browser resize 1280 720",
  "nova-engine browser click 12 --double",
  'nova-engine browser type 23 "hello" --submit',
  "nova-engine browser press Enter",
  "nova-engine browser hover 44",
  "nova-engine browser drag 10 11",
  "nova-engine browser select 9 OptionA OptionB",
  "nova-engine browser upload /tmp/nova-engine/uploads/file.pdf",
  'nova-engine browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "nova-engine browser dialog --accept",
  'nova-engine browser wait --text "Done"',
  "nova-engine browser evaluate --fn '(el) => el.textContent' --ref 7",
  "nova-engine browser console --level error",
  "nova-engine browser pdf",
];
